dist: xenial
language: python
python:
  - "3.7"
# command to install dependencies
install:
  - pip install lsbook
# command to run tests
script:
  - ls -l
  - lsbook -ba ../asserts -b --log debug .
after_success:
  - cd _book
  - ls -al
  - git init
  - git add .
  - git commit -m "Updated By Travis-CI With Build $TRAVIS_BUILD_NUMBER For Github Pages"
  - git push --force --quiet "https://${travis_ci_tokens}@${REF}" master:gh-pages
branches:
  only:
    - master
env:
  global:
    - REF=github.com/liushilive/github_software_testing_dictionary.git
before_install:
- export TZ='Asia/Shanghai'